# Versão da especificação do Docker Compose
version: "3.9"

services:
  # Serviço do Traefik (Proxy Reverso)
  traefik:
    image: traefik:v2.11 # Ou use 'latest'
    container_name: traefik_proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_proxy # Conecta à rede externa criada
    ports:
      - "80:80"   # Porta HTTP
      - "443:443" # Porta HTTPS
    environment:
      # --- Variáveis REMOVIDAS: CF_API_EMAIL, CF_DNS_API_TOKEN ---
      # Definindo PUID/PGID para permissões de arquivos
      - PUID=1000
      - PGID=1000
      # Fuso Horário lido do .env (com padrão)
      - TZ=${TIMEZONE:-America/Sao_Paulo}
      # Adicione aqui outras variáveis globais se precisar (ex: para outros provedores DNS se mudar o traefik.yml)
    volumes:
      # Mapeia o socket do Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mapeia a configuração estática (traefik.yml)
      - ./data/traefik.yml:/traefik.yml:ro
      # Mapeia a configuração dinâmica (opcional, descomente se usar)
      # - ./data/config.yml:/config.yml:ro
      # Mapeia o arquivo de certificados SSL
      - ./data/certs/acme.json:/acme.json
      # Mapeia os logs do Traefik
      - ./data/logs/traefik.log:/logs/traefik.log
    labels:
      # Habilita o Traefik para ele mesmo
      - "traefik.enable=true"
      # --- Configuração do Dashboard/API via Labels (Exemplo) ---
      # Se quiser habilitar o dashboard, descomente estas linhas
      # ATENÇÃO: Lembre-se de configurar autenticação (ex: basicauth abaixo)
      #- "traefik.http.routers.traefik-dashboard.rule=Host(`${TRAEFIK_SUBDOMAIN}.${DOMAINNAME}`)" # <<< USA VARIÁVEL DE SUBDOMÍNIO
      #- "traefik.http.routers.traefik-dashboard.service=api@internal"
      #- "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      #- "traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver"
      #- "traefik.http.routers.traefik-dashboard.middlewares=auth"
      # --- Autenticação Básica para Dashboard (Exemplo) ---
      # Crie um usuário/senha com htpasswd e cole aqui se usar o middleware 'auth'
      # Ex: htpasswd -nb usuario senhaforte | sed -e s/\\$/\\$\\$/g
      # - "traefik.http.middlewares.auth.basicauth.users=usuario:$$apr1$$...$$"

  # Serviço do Portainer CE (Gerenciador Docker)
  portainer:
    image: portainer/portainer-ce:latest # Ou uma versão específica
    container_name: portainer_manager
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_proxy # Conecta à rede externa também
    volumes:
      # Mapeia o socket do Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mapeia o volume de dados do Portainer
      - portainer_data:/data # Usa um volume nomeado
    labels:
      - "traefik.enable=true"
      # Roteia o tráfego para o Portainer (usando variável de subdomínio)
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_SUBDOMAIN}.${DOMAINNAME}`)" # <<< USA VARIÁVEL DE SUBDOMÍNIO
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443" # Porta interna do Portainer
      - "traefik.http.services.portainer.loadbalancer.server.scheme=https" # Portainer usa HTTPS interno
      - "traefik.http.routers.portainer.entrypoints=websecure" # Acessível via HTTPS
      - "traefik.http.routers.portainer.tls.certresolver=myresolver" # Usa o resolvedor Let's Encrypt definido no traefik.yml

# Define a rede externa
networks:
  traefik_proxy:
    external: true

# Define o volume nomeado para os dados do Portainer
volumes:
  portainer_data:
