# Configuração Estática do Traefik v2 (Usando HTTP-01 Challenge)

# Log
log:
  level: INFO
  filePath: /logs/traefik.log
  format: json

# API / Dashboard
api:
  dashboard: true
  # Acesso seguro via Rótulos no docker-compose.yml

# EntryPoints
entryPoints:
  web:
    address: ":80"
    # Redirecionamento HTTP para HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver # Nome do resolvedor abaixo
        # Os domínios serão gerenciados pelos routers (labels no compose)

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # Só expor containers com label traefik.enable=true
    network: traefik_proxy

# Certificate Resolvers (Como obter certificados SSL/TLS - Usando HTTP-01)
certificatesResolvers:
  myresolver: # Nome do resolvedor referenciado no compose
    acme:
      # Email para notificações Let's Encrypt (lido do .env)
      email: "${LETSENCRYPT_EMAIL}"
      storage: /acme.json # Caminho de armazenamento dos certificados
      # Método de Desafio HTTP-01 (Não precisa de API de DNS, usa a porta 80)
      httpChallenge:
        entryPoint: web # Usa o entrypoint 'web' (porta 80) para o desafio
